version: '3.8'

services:
  
  service-test-first-api:
    image: ${REGISTRY:-ukraine}/service-test-first-api:${TAG:-latest}
    build:
      context: .
      dockerfile: src/Services/Test/FirstTestApiService/Dockerfile
    depends_on:
      - component-postgresql
    networks:
      - ukraine-network
      
  service-test-second-api:
    image: ${REGISTRY:-ukraine}/service-test-second-api:${TAG:-latest}
    build:
      context: .
      dockerfile: src/Services/Test/SecondTestApiService/Dockerfile
    depends_on:
      - component-postgresql
    networks:
      - ukraine-network
      
  component-postgresql:
    image: postgres:14.4
    container_name: postgres_container
    networks:
      - ukraine-network
      
  component-zipkin:
    image: openzipkin/zipkin:latest
    container_name: zipkin
    networks:
      - ukraine-network
      
  component-seq:
    image: datalust/seq:latest
    container_name: seq
    networks:
      - ukraine-network
        
networks:
  ukraine-network: