version: '3.8'

services:

  zipkin:
    ports:
      - "9411:9411"

  seq:
    environment:
      - ACCEPT_EULA=Y
    ports:
      - "5341:80"

  postgresql:
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"

  service-identity:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - ConnectionStrings__ConfigurationDbConnection=Server=postgresql;Port=5432;Database=ukraine_identity;User Id=postgres;Password=postgres;
      - ConnectionStrings__PersistedGrantDbConnection=Server=postgresql;Port=5432;Database=ukraine_identity;User Id=postgres;Password=postgres;
      - ConnectionStrings__IdentityDbConnection=Server=postgresql;Port=5432;Database=ukraine_identity;User Id=postgres;Password=postgres;
      - ConnectionStrings__DataProtectionDbConnection=Server=postgresql;Port=5432;Database=ukraine_identity;User Id=postgres;Password=postgres;
      - Serilog__WriteTo__0__Name=Console
      - Serilog__WriteTo__1__Name=Seq
      - Serilog__WriteTo__1__Args__serverUrl=http://seq
    ports:
      - "7000:80"