version: '3.8'

services:
  
  service-test-first-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__Postgres=Server=postgres_container;Port=5432;Database=ukraine;User Id=postgres;Password=postgres;
      - ZipkinTelemetry__Endpoint=http://zipkin:9411/api/v2/spans
    ports:
      - "6050:6050"
    depends_on: 
    - component-zipkin
        
  service-test-second-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "6051:6051"
        
  component-postgresql:
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
        
  component-zipkin:
    ports:
      - "9411:9411"