version: '3.8'

services:

  zipkin:
    ports:
      - "9411:9411"

  seq:
    environment:
      - ACCEPT_EULA=Y
    ports:
      - "5341:80"

  postgresql:
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"

  rabbitmq:
    environment:
      RABBITMQ_DEFAULT_USER: "ukraine"
      RABBITMQ_DEFAULT_PASS: "ukraine"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "5672:5672"
      - "15672:15672"

  dapr-placement:
    command: ["./placement", "-port", "50000", "-log-level", "debug"]
    ports:
      - "50000:50000"

  service-identity:
    environment:
      - ASPNETCORE_ENVIRONMENT=${ENV_DOCKER_DEV}
      - ASPNETCORE_URLS=${LOCAL_WEB_URL}
    ports:
      - "7000:80"

  service-identity-dapr:
    command: ["./daprd",
              "-app-id", "service-identity",
              "-app-port", "80",
              "-placement-host-address", "dapr-placement:50000",
              "-components-path", "/components",
              "-config", "/components/ukraine-config.yaml"
    ]

  service-example:
    environment:
      - ASPNETCORE_ENVIRONMENT=${ENV_DOCKER_DEV}
      - ASPNETCORE_URLS=${LOCAL_WEB_URL}
    ports:
      - "7001:80"

  service-example-dapr:
    command: ["./daprd",
              "-app-id", "service-example",
              "-app-port", "80",
              "-placement-host-address", "dapr-placement:50000",
              "-components-path", "/components",
              "-config", "/components/ukraine-config.yaml"
    ]

  service-example-friend-registrar:
    environment:
      - ASPNETCORE_ENVIRONMENT=${ENV_DOCKER_DEV}
      - ASPNETCORE_URLS=${LOCAL_WEB_URL}
    ports:
      - "7002:80"

  service-example-friend-registrar-dapr:
    command: ["./daprd",
              "-app-id", "service-example-friend-registrar",
              "-app-port", "80",
              "-placement-host-address", "dapr-placement:50000",
              "-components-path", "/components",
              "-config", "/components/ukraine-config.yaml"
    ]

  web-status:
    environment:
      - ASPNETCORE_ENVIRONMENT=${ENV_DOCKER_DEV}
      - ASPNETCORE_URLS=${LOCAL_WEB_URL}
    ports:
      - "7003:80"

  gateway-graphql:
    environment:
      - ASPNETCORE_ENVIRONMENT=${ENV_DOCKER_DEV}
      - ASPNETCORE_URLS=${LOCAL_WEB_URL}
    ports:
      - "7004:80"

  maildev:
    ports:
      - "1080:1080"
      - "1025:1025"

  service-example-friend-email:
    environment:
      - ASPNETCORE_ENVIRONMENT=${ENV_DOCKER_DEV}
      - ASPNETCORE_URLS=${LOCAL_WEB_URL}
    ports:
      - "7005:80"

  service-example-friend-email-dapr:
    command: ["./daprd",
              "-app-id", "service-example-friend-email",
              "-app-port", "80",
              "-placement-host-address", "dapr-placement:50000",
              "-components-path", "/components",
              "-config", "/components/ukraine-config.yaml"
    ]