name: ukraine

extensions:

  - name: dapr
    log-level: debug
    config: ukraine-config
    components-path: ./dapr/components
    app-max-concurrency: 1
    services:
      service-test-first-api:
        enabled: true
      gateway-http:
        enabled: false
      web-status:
        enabled: false 
  - name: seq
    logPath: ./.logs

services:

  - name: component-postgresql
    image: postgres:14.4
    env:
      - name: POSTGRES_DB
        value: ukraine
      - name: POSTGRES_USER
        value: postgres
      - name: POSTGRES_PASSWORD
        value: postgres 
    bindings:
      - port: 5432
        connectionString: Server=${host};Port=${port};User Id=postgres;Password=${env:POSTGRES_PASSWORD};

  - name: service-example-api
    project: src/Services/Example/Ukraine.Services.Example.Api/Ukraine.Services.Example.Api.csproj
    env:
      - name: ASPNETCORE_ENVIRONMENT
        value: Development
    bindings:
      - port: 7002
         
  - name: gateway-http
    project: src/Gateways/Ukraine.Gateways.Http/Ukraine.Gateways.Http.csproj
    env:
      - name: ASPNETCORE_ENVIRONMENT
        value: Development
    bindings:
      - port: 7000
        
  - name: web-status
    project: src/Web/Ukraine.Web.Status/Ukraine.Web.Status.csproj
    env:
      - name: ASPNETCORE_ENVIRONMENT
        value: Development
    bindings:
      - port: 7001