# TODO REQUIRE UPDATE LATER
# missing maildev, friend-email

name: ukraine

extensions:

  - name: dapr
    log-level: debug
    config: ukraine-config
    components-path: ./dapr/components/local
    app-max-concurrency: 1
    services:
      gateway-http:
        enabled: false
      web-status:
        enabled: false
      gateway-graphql:
        enabled: false
  - name: seq
    logPath: ./.logs

services:

  - name: postgresql
    image: postgres:15.2-alpine3.17
    env:
      - name: POSTGRES_USER
        value: postgres
      - name: POSTGRES_PASSWORD
        value: postgres
    bindings:
      - port: 5432
        connectionString: Server=${host};Port=${port};User Id=postgres;Password=${env:POSTGRES_PASSWORD};
    replicas: 1

  - name: rabbitmq
    image: rabbitmq:3.11.10-management-alpine
    env:
      - name: RABBITMQ_DEFAULT_USER
        value: ukraine
      - name: RABBITMQ_DEFAULT_PASS
        value: ukraine
      - name: RABBITMQ_DEFAULT_VHOST
        value: /
    bindings:
      - name: ui
        protocol: http
        port: 15672
        containerPort: 15672
      - name: amqp
        protocol: amqp
        port: 5672
    replicas: 1

  - name: web-status
    project: src/Web/Ukraine.Web.Status/Ukraine.Web.Status.csproj
    env:
      - name: ASPNETCORE_ENVIRONMENT
        value: Development
    bindings:
      - port: 7003
    replicas: 1

  - name: service-identity
    project: src/Services/Identity/Ukraine.Services.Identity/Ukraine.Services.Identity.csproj
    env:
      - name: ASPNETCORE_ENVIRONMENT
        value: Development
    bindings:
      - port: 7000
    replicas: 1
    liveness:
      http:
        path: /health
      initialDelay: 1

  - name: service-example
    project: src/Services/Example/Ukraine.Services.Example.Api/Ukraine.Services.Example.Api.csproj
    env:
      - name: ASPNETCORE_ENVIRONMENT
        value: Development
    bindings:
      - port: 7001
    replicas: 1
    liveness:
      http:
        path: /health
      initialDelay: 1

  - name: service-example-friend-registrar
    project: src/Services/Example/Friends/Ukraine.Services.Example.Friends.Registrar/Ukraine.Services.Example.Friends.Registrar.csproj
    env:
      - name: ASPNETCORE_ENVIRONMENT
        value: Development
    bindings:
      - port: 7002
    replicas: 1
    liveness:
      http:
        path: /health
      initialDelay: 1

  - name: gateway-graphql
    project: src/Gateway/Ukraine.Gateway.GraphQl/Ukraine.Gateway.GraphQl.csproj
    env:
      - name: ASPNETCORE_ENVIRONMENT
        value: Development
    bindings:
      - port: 7004
    replicas: 1
    liveness:
      http:
        path: /health
      initialDelay: 1