name: ukraine

extensions:

  - name: dapr
    log-level: debug
    config: ukraine-config
    components-path: ./dapr/components
    app-max-concurrency: 1
    services:
      gateway-http:
        enabled: false
      web-status:
        enabled: false
  - name: seq
    logPath: ./.logs

services:

  - name: component-postgresql
    image: postgres:14.4
    env:
      - name: POSTGRES_DB
        value: ukraine
      - name: POSTGRES_USER
        value: postgres
      - name: POSTGRES_PASSWORD
        value: postgres
    bindings:
      - port: 5432
        connectionString: Server=${host};Port=${port};User Id=postgres;Password=${env:POSTGRES_PASSWORD};

  - name: component-rabbitmq
    image: rabbitmq:3-management
    bindings:
      - name: ui
        protocol: http
        port: 15672
        containerPort: 15672
      - name: amqp
        protocol: amqp
        port: 5672

  - name: web-status
    project: src/Web/Ukraine.Web.Status/Ukraine.Web.Status.csproj
    env:
      - name: ASPNETCORE_ENVIRONMENT
        value: Development
    bindings:
      - port: 7001

  - name: service-identity
    project: src/Services/Identity/Ukraine.Services.Identity/Ukraine.Services.Identity.csproj
    env:
      - name: ASPNETCORE_ENVIRONMENT
        value: Development
    bindings:
      - port: 7002

  - name: service-example-api
    project: src/Services/Example/Ukraine.Services.Example.Api/Ukraine.Services.Example.Api.csproj
    env:
      - name: ASPNETCORE_ENVIRONMENT
        value: Development
    bindings:
      - port: 7003

  - name: service-example-friend-registrar
    project: src/Services/Example/Friends/Ukraine.Services.Example.Friends.Registrar/Ukraine.Services.Example.Friends.Registrar.csproj
    env:
      - name: ASPNETCORE_ENVIRONMENT
        value: Development
    bindings:
      - port: 7004