apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: ukraine-config
  namespace: ukraine
spec:
  tracing:
    samplingRate: "1"
    zipkin:
      endpointAddress: "http://zipkin:9411/api/v2/spans"