// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Ukraine.Services.Example.Infrastructure.EfCore;

#nullable disable

namespace Ukraine.Services.Example.Infrastructure.EfCore.Migrations
{
    [DbContext(typeof(ExampleContext))]
    [Migration("20230202184021_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("example_schema")
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "uuid-ossp");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Ukraine.Services.Example.Domain.Entities.ExampleEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int?>("IntValue")
                        .HasColumnType("integer")
                        .HasColumnName("int_value");

                    b.Property<string>("StringValue")
                        .HasColumnType("text")
                        .HasColumnName("string_value");

                    b.HasKey("Id")
                        .HasName("pk_example_entities");

                    b.ToTable("example_entities", "example_schema");
                });
#pragma warning restore 612, 618
        }
    }
}
