// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Ukraine.Services.Example.Infrastructure.EfCore;

#nullable disable

namespace Ukraine.Services.Example.Infrastructure.EfCore.Migrations
{
    [DbContext(typeof(ExampleContext))]
    [Migration("20230203204620_ExampleChildEntity")]
    partial class ExampleChildEntity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("example_schema")
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "uuid-ossp");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Ukraine.Services.Example.Domain.Entities.ExampleChildEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ExampleEntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("example_entity_id");

                    b.Property<int>("NotNullIntValue")
                        .HasColumnType("integer")
                        .HasColumnName("not_null_int_value");

                    b.HasKey("Id")
                        .HasName("pk_example_child_entity");

                    b.HasIndex("ExampleEntityId")
                        .HasDatabaseName("ix_example_child_entity_example_entity_id");

                    b.ToTable("example_child_entity", "example_schema");
                });

            modelBuilder.Entity("Ukraine.Services.Example.Domain.Entities.ExampleEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int?>("IntValue")
                        .HasColumnType("integer")
                        .HasColumnName("int_value");

                    b.Property<string>("StringValue")
                        .HasColumnType("text")
                        .HasColumnName("string_value");

                    b.HasKey("Id")
                        .HasName("pk_example_entities");

                    b.ToTable("example_entities", "example_schema");
                });

            modelBuilder.Entity("Ukraine.Services.Example.Domain.Entities.ExampleChildEntity", b =>
                {
                    b.HasOne("Ukraine.Services.Example.Domain.Entities.ExampleEntity", "ExampleEntity")
                        .WithMany("ChildEntities")
                        .HasForeignKey("ExampleEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_example_child_entity_example_entities_example_entity_id");

                    b.Navigation("ExampleEntity");
                });

            modelBuilder.Entity("Ukraine.Services.Example.Domain.Entities.ExampleEntity", b =>
                {
                    b.Navigation("ChildEntities");
                });
#pragma warning restore 612, 618
        }
    }
}
